Point to master branch for examples
yewstack/docs pull request #98
Opened 2020-06-08 18:45 UTC by Darrenmeehan

While I'm assuming there was initially a reason for pinning the examples to a specific git tag, is this still the case?

2020-06-08 20:13 UTC, teymour-aldridge approved these changes

2020-06-09 01:39 UTC, jstarry commented
> While I'm assuming there was initially a reason for pinning the examples to a specific git tag, is this still the case?

Yeah, it's due to `master` periodically having breaking changes which conflict with the docs. The idea is that we pin examples and the docs to a particular version so that it's a consistent experience. That said, I need to make sure that this actually gets updated when releases go out. I'll add it to my release checklist, thanks for bring it up!

Could you change to the 0.16 branch?

2020-06-09 06:39 UTC, Darrenmeehan commented
That makes sense thanks for clarifying!

I'll happily update these later this evening.

2020-06-09 07:51 UTC, jstarry commented
No problem, thank you!

2020-06-17 09:57 UTC, teymour-aldridge requested changes

2020-06-17 09:57 UTC, teymour-aldridge commented on src/getting-started/examples.md
> +* [**Todo App** ](https://github.com/yewstack/yew/tree/master/examples/todomvc)
```suggestion
* [**Todo App** ](https://github.com/yewstack/yew/tree/v0.16.0/examples/todomvc)
```

2020-06-17 09:57 UTC, teymour-aldridge commented on src/getting-started/examples.md
> +* [**Custom Components**](https://github.com/yewstack/yew/tree/master/examples/custom_components)
```suggestion
* [**Custom Components**](https://github.com/yewstack/yew/tree/v0.16.0/examples/custom_components)
```

2020-06-17 09:57 UTC, teymour-aldridge commented on src/getting-started/examples.md
> +* [**Multi-threading \(Agents\)**](https://github.com/yewstack/yew/tree/master/examples/multi_thread)
```suggestion
* [**Multi-threading \(Agents\)**](https://github.com/yewstack/yew/tree/v0.16.0/examples/multi_thread)
```

2020-06-17 09:57 UTC, teymour-aldridge commented on src/getting-started/examples.md
> +* [**Timer Service**](https://github.com/yewstack/yew/tree/master/examples/timer)
```suggestion
* [**Timer Service**](https://github.com/yewstack/yew/tree/v0.16.0/examples/timer)
```

2020-06-17 09:57 UTC, teymour-aldridge commented on src/getting-started/examples.md
> +* [**Nested Components**](https://github.com/yewstack/yew/tree/master/examples/nested_list)
```suggestion
* [**Nested Components**](https://github.com/yewstack/yew/tree/v0.16.0/examples/nested_list)
```

2020-06-20 15:34 UTC, jstarry commented on src/getting-started/examples.md
> +The Yew repository is chock-full of [examples](https://github.com/yewstack/yew/tree/master/examples) \(in various states of maintenance\). We recommend perusing them to get a feel for how to use diff
```suggestion
The Yew repository is chock-full of [examples](https://github.com/yewstack/yew/tree/v0.16.0/examples) \(in various states of maintenance\). We recommend perusing them to get a feel for how to use different framework features. We also welcome pull-requests and issues for when they inevitably get neglected and need some ♥️
```

2020-06-20 15:34 UTC, merged